export const trainerQuotes = [
  "Catch ‘em with courage!",
  "Every day’s a new journey.",
  "Strong bonds make strong teams.",
  "Don’t chase power, chase growth.",
  "Adventure begins with one step.",
  "Even legends start small.",
  "Friendship beats strength.",
  "Every throw counts.",
  "Never stop exploring.",
  "A true trainer never quits.",
  "Keep going, the rare ones await.",
  "Battles teach more than victories.",
  "Stay sharp, stay kind.",
  "Patience catches greatness.",
  "The next encounter could be special.",
  "Every failure is training.",
  "Your team believes in you.",
  "Weather the storm, find the prize.",
  "Courage makes the best Poké Ball.",
  "No journey is wasted.",
  "The best trainers learn daily.",
  "Every Pokémon is unique.",
  "Stay curious, stay ready.",
  "Legends are caught by dreamers.",
  "Believe in your next catch."
];
